# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created: Sun Feb 24 19:25:11 2013
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(878, 672)
        MainWindow.setTabShape(QtGui.QTabWidget.Rounded)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.lbl_note = QtGui.QLabel(self.centralwidget)
        self.lbl_note.setGeometry(QtCore.QRect(90, 10, 331, 16))
        self.lbl_note.setObjectName(_fromUtf8("lbl_note"))
        self.frame_content = QtGui.QFrame(self.centralwidget)
        self.frame_content.setGeometry(QtCore.QRect(10, 80, 841, 551))
        self.frame_content.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_content.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_content.setObjectName(_fromUtf8("frame_content"))
        self.lbl_title = QtGui.QLabel(self.frame_content)
        self.lbl_title.setGeometry(QtCore.QRect(20, 9, 621, 21))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_title.sizePolicy().hasHeightForWidth())
        self.lbl_title.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setUnderline(False)
        self.lbl_title.setFont(font)
        self.lbl_title.setTextFormat(QtCore.Qt.PlainText)
        self.lbl_title.setScaledContents(False)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_title.setObjectName(_fromUtf8("lbl_title"))
        self.formLayoutWidget = QtGui.QWidget(self.frame_content)
        self.formLayoutWidget.setGeometry(QtCore.QRect(20, 50, 251, 70))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lbl_author = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_author.setObjectName(_fromUtf8("lbl_author"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.lbl_author)
        self.lbl_static_type = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_static_type.setObjectName(_fromUtf8("lbl_static_type"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.lbl_static_type)
        self.lbl_art_type = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_art_type.setObjectName(_fromUtf8("lbl_art_type"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lbl_art_type)
        self.lbl_static_date = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_static_date.setObjectName(_fromUtf8("lbl_static_date"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.lbl_static_date)
        self.lbl_date = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_date.setObjectName(_fromUtf8("lbl_date"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lbl_date)
        self.lbl_static_author = QtGui.QLabel(self.formLayoutWidget)
        self.lbl_static_author.setObjectName(_fromUtf8("lbl_static_author"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lbl_static_author)
        self.verticalLayoutWidget = QtGui.QWidget(self.frame_content)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(290, 50, 351, 461))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.lbl_static_preview = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_preview.sizePolicy().hasHeightForWidth())
        self.lbl_static_preview.setSizePolicy(sizePolicy)
        self.lbl_static_preview.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_static_preview.setObjectName(_fromUtf8("lbl_static_preview"))
        self.verticalLayout.addWidget(self.lbl_static_preview)
        self.lbl_preview_img = QtGui.QLabel(self.verticalLayoutWidget)
        self.lbl_preview_img.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_preview_img.setObjectName(_fromUtf8("lbl_preview_img"))
        self.verticalLayout.addWidget(self.lbl_preview_img)
        self.lbl_description = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_description.sizePolicy().hasHeightForWidth())
        self.lbl_description.setSizePolicy(sizePolicy)
        self.lbl_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_description.setWordWrap(True)
        self.lbl_description.setObjectName(_fromUtf8("lbl_description"))
        self.verticalLayout.addWidget(self.lbl_description)
        self.lbl_static_attribution = QtGui.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_static_attribution.sizePolicy().hasHeightForWidth())
        self.lbl_static_attribution.setSizePolicy(sizePolicy)
        self.lbl_static_attribution.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_static_attribution.setWordWrap(False)
        self.lbl_static_attribution.setObjectName(_fromUtf8("lbl_static_attribution"))
        self.verticalLayout.addWidget(self.lbl_static_attribution)
        self.lbl_attribution = QtGui.QLabel(self.verticalLayoutWidget)
        self.lbl_attribution.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lbl_attribution.setWordWrap(True)
        self.lbl_attribution.setObjectName(_fromUtf8("lbl_attribution"))
        self.verticalLayout.addWidget(self.lbl_attribution)
        self.line = QtGui.QFrame(self.frame_content)
        self.line.setGeometry(QtCore.QRect(160, 30, 381, 20))
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.verticalLayoutWidget_2 = QtGui.QWidget(self.frame_content)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(20, 130, 251, 381))
        self.verticalLayoutWidget_2.setObjectName(_fromUtf8("verticalLayoutWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.lbl_static_licenses = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lbl_static_licenses.setObjectName(_fromUtf8("lbl_static_licenses"))
        self.verticalLayout_2.addWidget(self.lbl_static_licenses)
        self.list_licenses = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.list_licenses.setFocusPolicy(QtCore.Qt.NoFocus)
        self.list_licenses.setSelectionMode(QtGui.QAbstractItemView.NoSelection)
        self.list_licenses.setResizeMode(QtGui.QListView.Adjust)
        self.list_licenses.setObjectName(_fromUtf8("list_licenses"))
        self.verticalLayout_2.addWidget(self.list_licenses)
        self.lbl_static_files = QtGui.QLabel(self.verticalLayoutWidget_2)
        self.lbl_static_files.setObjectName(_fromUtf8("lbl_static_files"))
        self.verticalLayout_2.addWidget(self.lbl_static_files)
        self.list_files = QtGui.QListWidget(self.verticalLayoutWidget_2)
        self.list_files.setSelectionMode(QtGui.QAbstractItemView.MultiSelection)
        self.list_files.setObjectName(_fromUtf8("list_files"))
        self.verticalLayout_2.addWidget(self.list_files)
        self.btn_download = QtGui.QPushButton(self.verticalLayoutWidget_2)
        self.btn_download.setObjectName(_fromUtf8("btn_download"))
        self.verticalLayout_2.addWidget(self.btn_download)
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(49, 30, 771, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.lbl_link_here = QtGui.QLabel(self.horizontalLayoutWidget)
        self.lbl_link_here.setObjectName(_fromUtf8("lbl_link_here"))
        self.horizontalLayout.addWidget(self.lbl_link_here)
        self.linein_url = QtGui.QLineEdit(self.horizontalLayoutWidget)
        self.linein_url.setMaxLength(1000)
        self.linein_url.setObjectName(_fromUtf8("linein_url"))
        self.horizontalLayout.addWidget(self.linein_url)
        self.btn_get = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.btn_get.setObjectName(_fromUtf8("btn_get"))
        self.horizontalLayout.addWidget(self.btn_get)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 878, 20))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "OGA Downloader", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_note.setText(QtGui.QApplication.translate("MainWindow", "Note: Does not work for textures!", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_title.setText(QtGui.QApplication.translate("MainWindow", "Title", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_author.setText(QtGui.QApplication.translate("MainWindow", "Author here", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_type.setText(QtGui.QApplication.translate("MainWindow", "Art type:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_art_type.setText(QtGui.QApplication.translate("MainWindow", "Art type here", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_date.setText(QtGui.QApplication.translate("MainWindow", "Date:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_date.setText(QtGui.QApplication.translate("MainWindow", "Date here", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_author.setText(QtGui.QApplication.translate("MainWindow", "Author:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_preview.setText(QtGui.QApplication.translate("MainWindow", "Preview:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_preview_img.setText(QtGui.QApplication.translate("MainWindow", "Preview image here", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_description.setText(QtGui.QApplication.translate("MainWindow", "Description here", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_attribution.setText(QtGui.QApplication.translate("MainWindow", "Attribution instructions:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_attribution.setText(QtGui.QApplication.translate("MainWindow", "Attribution instructions here", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_licenses.setText(QtGui.QApplication.translate("MainWindow", "Licenses:", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_static_files.setText(QtGui.QApplication.translate("MainWindow", "Files:", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_download.setText(QtGui.QApplication.translate("MainWindow", "Download!", None, QtGui.QApplication.UnicodeUTF8))
        self.lbl_link_here.setText(QtGui.QApplication.translate("MainWindow", "URL:", None, QtGui.QApplication.UnicodeUTF8))
        self.linein_url.setPlaceholderText(QtGui.QApplication.translate("MainWindow", "Copy url here", None, QtGui.QApplication.UnicodeUTF8))
        self.btn_get.setText(QtGui.QApplication.translate("MainWindow", "Get!", None, QtGui.QApplication.UnicodeUTF8))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

